// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtP-urzAJN4BNJJr9m0O91pM1fqo4Vnbg',
    appId: '1:780002452262:android:0f1b4fb8cfab2445bd17e7',
    messagingSenderId: '780002452262',
    projectId: 'forsa-food-b6b50',
    databaseURL: 'https://forsa-food-b6b50-default-rtdb.firebaseio.com',
    storageBucket: 'forsa-food-b6b50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTuAVE8cvPwUrjHz7f-Ub6M4rdJiqTitA',
    appId: '1:780002452262:ios:b3a8d662e0432d14bd17e7',
    messagingSenderId: '780002452262',
    projectId: 'forsa-food-b6b50',
    databaseURL: 'https://forsa-food-b6b50-default-rtdb.firebaseio.com',
    storageBucket: 'forsa-food-b6b50.firebasestorage.app',
    androidClientId: '780002452262-bip4doo7ek02mus1avsb3t5nv9uf7256.apps.googleusercontent.com',
    iosClientId: '780002452262-epd461jg33nmg1a81asmsqcgv1q9ar5l.apps.googleusercontent.com',
    iosBundleId: 'com.foodies.restaurant.ios',
  );

}